import { Prisma } from '@prisma/client';
import { IsEmail, IsString } from 'class-validator';
/**
 * Data transfer object for creating a user
 * @classdesc Data transfer object for creating a user
 * @property {string} id - The user's id is generated by the database
 * @property {string} email - The user's email and is required
 * @property {string} password - The user's password and is required
 * @property {string} name - The user's name and is required
 * @property {Date | string} createdAt - The date and time the user was created generated by the database
 * @property {Date | string} updatedAt - The date and time the user was last updated generated by the database
 */
export class CreateUserDto {
  id?: string;
  @IsEmail()
  email: string;
  @IsString()
  password: string;
  @IsString()
  @IsString()
  name: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  playlists?: Prisma.PlaylistCreateNestedManyWithoutUserInput;
}
