/**
 * Descrription of User
 * @classdesc Descrription of User
 * @property {string} id - The user's id is generated by the database
 * @property {string} email - The user's email and is required
 * @property {string} password - The user's password and is required
 * @property {string} name - The user's name and is required
 * @property {Date | string} createdAt - The date and time the user was created generated by the database
 * @property {Date | string} updatedAt - The date and time the user was last updated generated by the database
 */
export default interface IUser {
  id?: string;
  email: string;
  password: string;
  name: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  playlists?: [];
}
